# Jekyll Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site settings
# title appears in the header
#title: Collection Title
# tagline appears in the header, should be short
#tagline: "Digital collection generator"
# description is for metadata tags
# might appear in search result lists, keep around 160 characters max
#description: "Bigger description about synopsis..."
# for metatags
keywords: university of idaho, digital collections
# contact person
email: ewilliamson@uidaho.edu

title: Psychiana Digital Collection
tagline: Materials from the Frank B. Robinson Papers documenting Psychiana, a religion popular in the 1930s and 40s
subjects:  #separate semi-colon(';')
description: "Materials from the Frank B. Robinson Papers documenting Psychiana, a religion popular in the 1930s and 40s" 
mediatypes: images; documents; audio; correspondence #options[documents,images,video,sound,data] separate semi-colon(';')
locations: Moscow, ID #separate by semi-colon(';')
latitude: 46.733711 #to determine center of map
longitude: -117.001252 #to determine center of map



# images
# banner-image appears in index header
banner-image: /assets/example.jpg
# featured-image appears in meta tags
# represents the collection in other aggregations
featured-image: http://digital.lib.uidaho.edu/utils/ajaxhelper/?CISOROOT=psychiana&CISOPTR=548&action=2&DMSCALE=80&DMWIDTH=2000&DMHEIGHT=800&DMX=0&DMY=0&DMTEXT=&DMROTATE=0

# url variables
# library's domain (only changed if using github pages)
url: https://www.lib.uidaho.edu
# location on the website, normally in /digital
# e.g. /digital/hjccc
baseurl: /digital/psychiana
# CDM collection alias
collection-id: psychiana
# Objects dir location
objects: https://www.lib.uidaho.edu/digital/objects/

# repository variables (leave blank if self-contained)
repo-url: https://digital.lib.uidaho.edu 
repo-collection-id: psychiana
repo-link: #options[on] - if on, will link to base repository item url outside of directory; if blank, will link to item url within directory, which will require the page-gen settings to be turned on below-- NOTE: these item pages will not work via Github Pages


# url for our CDM server
cdm-url: https://digital.lib.uidaho.edu
# url to the shared assets folder on Digital
digital-assets: https://www.lib.uidaho.edu/digital/assets

# Theme Options
# navbar text color
# Choose from "navbar-light" for use with light background colors, or "navbar-dark" for dark background colors
navbar-color: navbar-dark
# navbar background color
# Choose from bg-primary, bg-secondary, bg-success, bg-danger, bg-warning, bg-info, bg-light, bg-dark, bg-white
navbar-background: bg-secondary
# theme with Bootswatch (https://github.com/thomaspark/bootswatch)
# Choose from: cerulean; cosmo; cyborg; darkly; flatly; journal; litera; lumen; lux; materia; minty; pulse; sandstone; simplex; sketchy; slate; solar; spacelab; superhero; united; yeti 
bootswatch: materia # leave blank or comment out for plain bootstrap

# Dev variables: 
# choose metadata set, i.e. easily switch between full or dev version
# be sure to also change page_gen data setting!
metadata: psychiana

# collection display variables 
# see _data/metadata-config.csv

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'psychiana'
    template: 'items'
    name: 'object-id'
    dir: 'data'
    extension: 'html'    
